# ALL-USE Development Configuration

# System Configuration
system:
  name: "ALL-USE Agent System"
  version: "1.0.0-dev"
  environment: "development"
  debug: true

# Logging Configuration
logging:
  level: "DEBUG"
  format: "text"
  rotation:
    max_size: "5MB"
    backup_count: 3
  outputs:
    - "console"

# Performance Configuration
performance:
  cache:
    max_size: 100
    ttl_seconds: 1800
  memory:
    gc_threshold: 0.9
    max_memory_mb: 256
  async:
    max_workers: 5
    timeout_seconds: 60

# Monitoring Configuration
monitoring:
  metrics:
    collection_interval: 5
    retention_hours: 12
  health:
    check_interval: 60
    timeout_seconds: 10
  alerts:
    enabled: false

# Component Configuration
components:
  agent_core:
    response_timeout: 200
    memory_limit_mb: 64
  
  trading_engine:
    analysis_timeout: 100
    cache_enabled: true
  
  risk_management:
    monitoring_interval: 50
    alert_threshold: 0.8
  
  optimization:
    auto_optimize: false
    optimization_interval: 600

# Security Configuration
security:
  input_validation: true
  error_sanitization: false
  log_sanitization: false

# Development Settings
development:
  hot_reload: true
  test_mode: true
  mock_external_services: true

