# ALL-USE Production Configuration

# System Configuration
system:
  name: "ALL-USE Agent System"
  version: "1.0.0"
  environment: "production"
  debug: false

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  rotation:
    max_size: "10MB"
    backup_count: 5
  outputs:
    - "file"
    - "console"

# Performance Configuration
performance:
  cache:
    max_size: 1000
    ttl_seconds: 3600
  memory:
    gc_threshold: 0.8
    max_memory_mb: 512
  async:
    max_workers: 10
    timeout_seconds: 30

# Monitoring Configuration
monitoring:
  metrics:
    collection_interval: 1
    retention_hours: 24
  health:
    check_interval: 30
    timeout_seconds: 5
  alerts:
    enabled: true
    severity_levels:
      - "critical"
      - "warning"
      - "info"

# Component Configuration
components:
  agent_core:
    response_timeout: 100
    memory_limit_mb: 128
  
  trading_engine:
    analysis_timeout: 50
    cache_enabled: true
  
  risk_management:
    monitoring_interval: 25
    alert_threshold: 0.9
  
  optimization:
    auto_optimize: true
    optimization_interval: 300

# Security Configuration
security:
  input_validation: true
  error_sanitization: true
  log_sanitization: true

# Production Deployment
deployment:
  health_check_path: "/health"
  metrics_path: "/metrics"
  graceful_shutdown_timeout: 30
  startup_timeout: 60

